package com.msb.system.info;

import javax.persistence.*;
import java.util.Date;

//和数据库对应
@Entity
@Table(name="t_user")
public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Column(name="uname")//数据库表字段
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uaccount
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Column
    private String uaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.upass
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Column
    private String upass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.umail
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Column
    private String umail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uphone
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Column
    private String uphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.t1
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Column
    private String t1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.desc
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    @Column
    private String udesc;
    @Column
    private int ustatus;
    @Column
    private String utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uid
     *
     * @return the value of t_user.uid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uid
     *
     * @param uid the value for t_user.uid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uname
     *
     * @return the value of t_user.uname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uname
     *
     * @param uname the value for t_user.uname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uaccount
     *
     * @return the value of t_user.uaccount
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getUaccount() {
        return uaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uaccount
     *
     * @param uaccount the value for t_user.uaccount
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setUaccount(String uaccount) {
        this.uaccount = uaccount == null ? null : uaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.upass
     *
     * @return the value of t_user.upass
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.upass
     *
     * @param upass the value for t_user.upass
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setUpass(String upass) {
        this.upass = upass == null ? null : upass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.umail
     *
     * @return the value of t_user.umail
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getUmail() {
        return umail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.umail
     *
     * @param umail the value for t_user.umail
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setUmail(String umail) {
        this.umail = umail == null ? null : umail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.uphone
     *
     * @return the value of t_user.uphone
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.uphone
     *
     * @param uphone the value for t_user.uphone
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setUphone(String uphone) {
        this.uphone = uphone == null ? null : uphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.t1
     *
     * @return the value of t_user.t1
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getT1() {
        return t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.t1
     *
     * @param t1 the value for t_user.t1
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setT1(String t1) {
        this.t1 = t1 == null ? null : t1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.desc
     *
     * @return the value of t_user.desc
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getDesc() {
        return udesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.desc
     *
     * @param udesc the value for t_user.desc
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setDesc(String udesc) {
        this.udesc = udesc == null ? null : udesc.trim();
    }


    public String getUtime() {
        return utime;
    }

    public void setUtime(String utime) {
        this.utime = utime;
    }

    public int getUstatus() {
        return ustatus;
    }

    public void setUstatus(int ustatus) {
        this.ustatus = ustatus;
    }
}