package com.msb.api.entity;

public class AuthEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.aid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.aname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.apath
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private String apath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.atype
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private Integer atype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.pid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.aid
     *
     * @return the value of t_auth.aid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.aid
     *
     * @param aid the value for t_auth.aid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.aname
     *
     * @return the value of t_auth.aname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.aname
     *
     * @param aname the value for t_auth.aname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.apath
     *
     * @return the value of t_auth.apath
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getApath() {
        return apath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.apath
     *
     * @param apath the value for t_auth.apath
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setApath(String apath) {
        this.apath = apath == null ? null : apath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.atype
     *
     * @return the value of t_auth.atype
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public Integer getAtype() {
        return atype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.atype
     *
     * @param atype the value for t_auth.atype
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setAtype(Integer atype) {
        this.atype = atype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.pid
     *
     * @return the value of t_auth.pid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.pid
     *
     * @param pid the value for t_auth.pid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}