package com.msb.api.entity;

public class RoleEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.rid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.rname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private String rname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.rtype
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private String rtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.rdesc
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    private String rdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.rid
     *
     * @return the value of t_role.rid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.rid
     *
     * @param rid the value for t_role.rid
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.rname
     *
     * @return the value of t_role.rname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.rname
     *
     * @param rname the value for t_role.rname
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.rtype
     *
     * @return the value of t_role.rtype
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getRtype() {
        return rtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.rtype
     *
     * @param rtype the value for t_role.rtype
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setRtype(String rtype) {
        this.rtype = rtype == null ? null : rtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.rdesc
     *
     * @return the value of t_role.rdesc
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public String getRdesc() {
        return rdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.rdesc
     *
     * @param rdesc the value for t_role.rdesc
     *
     * @mbggenerated Wed Jun 01 10:30:34 CST 2022
     */
    public void setRdesc(String rdesc) {
        this.rdesc = rdesc == null ? null : rdesc.trim();
    }
}